### ISSUE TITLE
Propose adding `nonRepudiation`, `digitalSignature`, `keyEncipherment` key usage attributes for leaf certificates 

### ISSUE THREAD

**Issue by ajessup** [spiffe/svid#1]
(Originally proposed by @rra - making sure it's captured here so we don't loose track of it)

Currently `Digital Signature`, `Key Encipherment`, `cRLSign` are marked as critical for Key Usage.

These are specifically for the CAs (and it looks like we want `keyCertSign` as well).

For the leaf certificates, `nonRepudiation`, `digitalSignature`, `keyEncipherment` seems reasonable

**Comment by diogomonica** [comment]
I think `nonRepudiation` is for SMIME stuff and intended originally to sign documents. Why do we want it?

**Comment by ajessup** [comment]
Closed in #2
