### ISSUE TITLE
Is there a reference implementation ?

### ISSUE THREAD

**Issue by indykish** [spiffe/svid#3]
Are you guys  

1. Making a ref. impl (or) 
2. SPIFFE will make one (or) 
3. Any one else will implement it ?

**Comment by zoidbergwill** [comment]
The README implies there is one, I think there used to one but the repo went private.

> You [can] find a list of issues under discussion in the agenda and minutes of the SIG, if you want to participate learn how to join.

Then the link to the SIG 404s though: https://github.com/spiffe/community/blob/master/sig-list.md

**Comment by indykish** [comment]
Ok. thanks

**Comment by ajessup** [comment]
Hey folks, good question - we (a set of SPIFFE design partners) are working on a reference implementation as we speak. As the design is in flux right now we haven't made too much public, but expect to start publishing some usable code, along with a roadmap, in a couple of months at https://spiffe.io/. 

The SIG link is to a private (for now) repo, hence the 404. We'll be opening it up shortly. If you're interested in getting involved earlier, drop me a line at andrew AT scytale.io.
